function propInfoFile(cnv, mosaicConeInfo)
% Save pertinent info in its own jpeg image for ready viewing, under the
% same name as the render structure itself. 

A = [...
mosaicConeInfo.regionVariant; ...
mosaicConeInfo.regionWidths; ...
mosaicConeInfo.numTotal; ...

mosaicConeInfo.numL; ...
mosaicConeInfo.numM; ...
mosaicConeInfo.numS; ...

mosaicConeInfo.targetPropsL; ...
mosaicConeInfo.targetPropsM; ...
mosaicConeInfo.targetPropsS; ...

mosaicConeInfo.achievedPropsL; ...
mosaicConeInfo.achievedPropsM; ...
mosaicConeInfo.achievedPropsS; ...

mosaicConeInfo.targetPropsLOfWholeMosaic; ...
mosaicConeInfo.targetPropsMOfWholeMosaic; ...
mosaicConeInfo.targetPropsSOfWholeMosaic; ...

mosaicConeInfo.achievedPropsLOfWholeMosaic; ...
mosaicConeInfo.achievedPropsMOfWholeMosaic; ...
mosaicConeInfo.achievedPropsSOfWholeMosaic; ...
];

T = array2table(A, 'VariableNames', {'Center' 'Near Surround' 'Distant Surround'}, ...
    'RowNames', {'Region Variant' 'Region Widths' 'Total Cones' ...
    'Num L' 'Num M' 'Num S' ...
    'Target Prop L' 'Target Prop M' 'Target Prop S' ...
    'Achieved Prop L' 'Achieved Prop M' 'Achieved Prop S' ...
    'Target Prop L Whole' 'Target Prop M Whole' 'Target Prop S Whole' ...
    'Achieved Prop L Whole' 'Achieved Prop M Whole' 'Achieved Prop S Whole'});

txtLocation = fullfile(cnv.forwardRenderDirFull, cnv.renderName); 

fig = uifigure;
uit = uitable(fig, "Data", T);
s = uistyle('HorizontalAlignment', 'left');
addStyle(uit, s);

% Some fancy resizing to spruce up the output. Should note: you need the 
% drawnow as well to get appropriate loading of the images. 
drawnow
fig.Position = [50 456 768 545];

drawnow
fig.AutoResizeChildren = 'off';

drawnow
fig.Position = [53 456 547 461];

exportapp(fig, [txtLocation(1:end-4) '.jpeg'])

end
